// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gszrfiwmtisbiltcmroa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzenJmaXdtdGlzYmlsdGNtcm9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MjI5NDksImV4cCI6MjA2NDE5ODk0OX0.VbopvVSxSf3UU8XyiMecXykGE6FPb2nNZ-TfQeFOiY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);